spring.mvc:
  static-path-pattern: "/static/**"
  resources.static-locations: "classpath:/static"

confirmation-channels.email:
  smtp:
    # If you are using your university's corporate email as provider for this app then use the following values:
    #
    # host: smtp.office365.com
    # port: 587
    #
    host: "<smtp_host>"
    port: "<smtp_port>"
    sender: "<email_sender>"
    username: "<smtp_username>"
    password: "<smtp_password>"
